server:
  port: 8001
spring:
  application:
    name: userServiceProvider
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: userServiceProvider
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clouddb01?serverTimezone=UTC
    username: root
    password: 606058zb
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

mybatis-plus:
  type-aliases-package: com.seele.springcloud.entity
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: false
