server:
  port: 8004
spring:
  application:
    name: testredis
#  cloud:
#    consul:
#      host: localhost
#      port: 8500
#      discovery:
#        service-name: userServiceProvider
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clouddb01?serverTimezone=UTC
    username: root
    password: 606058zb
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 100
        max-idle: 10
        max-wait: 1000000

mybatis-plus:
  type-aliases-package: com.seele.springcloud.entity
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: false

